//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TallerFinal.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TallerFinal.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap caja_ico {
            get {
                object obj = ResourceManager.GetObject("caja.ico", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_clip_art_inventory_management_software_inventory_c_apakah_manajemen_inventory_itu_penting_article_5c0bfccfb7f956_3592651915442894877536 {
            get {
                object obj = ResourceManager.GetObject("kisspng-clip-art-inventory-management-software-inventory-c-apakah-manajemen-inven" +
                        "tory-itu-penting-article-5c0bfccfb7f956.3592651915442894877536", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_computer_icons_arrow_left_arrow_5ac5e89fdffdc1_8459894415229195839175 {
            get {
                object obj = ResourceManager.GetObject("kisspng-computer-icons-arrow-left-arrow-5ac5e89fdffdc1.8459894415229195839175", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_ergonomics_in_the_warehouse_warehouse_management_s_5b0a65b6ec0273_3397523715274080549667 {
            get {
                object obj = ResourceManager.GetObject("kisspng-ergonomics-in-the-warehouse-warehouse-management-s-5b0a65b6ec0273.3397523" +
                        "715274080549667", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_handyman_home_repair_vector_graphics_clip_art_illu_ampquotampquot_5cbed0c75bde19_4819056815560091593763 {
            get {
                object obj = ResourceManager.GetObject("kisspng-handyman-home-repair-vector-graphics-clip-art-illu-ampquotampquot-5cbed0c" +
                        "75bde19.4819056815560091593763", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_inventory_management_software_inventory_control_ca_inventory_management_5b3f7886a8ad85_8414975115308862786909 {
            get {
                object obj = ResourceManager.GetObject("kisspng-inventory-management-software-inventory-control-ca-inventory-management-5" +
                        "b3f7886a8ad85.8414975115308862786909", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_inventory_management_software_inventory_turnover_g_inventory_management_5b38fde2592084_5869066315304616663651 {
            get {
                object obj = ResourceManager.GetObject("kisspng-inventory-management-software-inventory-turnover-g-inventory-management-5" +
                        "b38fde2592084.5869066315304616663651", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_inventory_management_software_warehouse_management_inventory_management_5b43314a90e3b5_9336076715311301865935 {
            get {
                object obj = ResourceManager.GetObject("kisspng-inventory-management-software-warehouse-management-inventory-management-5" +
                        "b43314a90e3b5.9336076715311301865935", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_zoho_office_suite_zoho_corporation_customer_relati_inventory_management_software_5b1d3843aa29b1_129569411528641603697 {
            get {
                object obj = ResourceManager.GetObject("kisspng-zoho-office-suite-zoho-corporation-customer-relati-inventory-management-s" +
                        "oftware-5b1d3843aa29b1.129569411528641603697", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
